version: '3.8'

services:
  web-server-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-server-app
    depends_on:
      - web-server-db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "3000:3000"
    volumes:
      - app-data:/var/app/logs
    restart: unless-stopped
    networks:
      - log-monitor-network

  web-server-db:
    image: postgres:15
    container_name: web-server-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - log-monitor-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.1
    container_name: filebeat
    user: root
    ports:
      - "5066:5066"
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - app-data:/var/app/logs:ro
      - filebeat-data:/usr/share/filebeat/data 
    environment:
      - KAFKA_BROKERS=kafka-server:9092
      - KAFKA_TOPIC=web-server-logs
    command: [ "--strict.perms=false" ]
    depends_on:
      - web-server-app
    networks:
      - log-monitor-network
  
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.13.1
    container_name: metricbeat
    user: root
    volumes:
      - ./metricbeat/metricbeat.yaml:/usr/share/metricbeat/metricbeat.yml:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5067:5067"
    depends_on:
      - filebeat
    networks:
      - log-monitor-network

  
volumes:
  app-data: {}
  pgdata:
  filebeat-data: {}

networks:
  log-monitor-network:
    name: log-monitor-network
    driver: bridge
