{
 "title": "Final Updated Benchmark",
 "time": { "from": "2025-07-18T06:16:30.000Z", "to": "2025-07-18T06:18:30.000Z" },
 "panels": [
  { "title": "ClickHouse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stored Data Size",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "rawSql": "SELECT \n  table,\n  sum(bytes_on_disk) / 1024 / 1024 AS size\nFROM system.parts\nWHERE active AND database = 'default'\nGROUP BY table\nORDER BY size DESC;\n"
    }
   ]
  },
  {
   "title": "Query Execution TIme",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \n  toStartOfInterval(event_time, INTERVAL 15 second) AS time_bucket,\n  quantile(0.50)(query_duration_ms) AS p50_ms,\n  quantile(0.95)(query_duration_ms) AS p95_ms,\n  quantile(0.99)(query_duration_ms) AS p99_ms,\n  avg(query_duration_ms) AS avg_ms,\n  min(query_duration_ms) AS min_ms,\n  max(query_duration_ms) AS max_ms\nFROM system.query_log\nWHERE event_time >= now() - INTERVAL 1 hour\n  AND type = 'QueryFinish'\nGROUP BY time_bucket\nORDER BY time_bucket;\n"
    }
   ]
  },
  {
   "title": "Query Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT \n  toStartOfInterval(event_time, INTERVAL 15 second) AS time_bucket,\n  count() / 60.0 AS qps\nFROM system.query_log\nWHERE event_time >= now() - INTERVAL 1 hour\n  AND type = 'QueryFinish'\nGROUP BY time_bucket\nORDER BY time_bucket;\n"
    }
   ]
  },
  {
   "title": "Number of Stored Data",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM web_server_logs"
    }
   ]
  },
  { "title": "Resources Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Usage per Container (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\"flink-jobmanager-1|flink-taskmanager-1|flink-app-1|kafka-server|zookeeper|fluentbit|clickhouse|web-server-app|web-server-db|grafana\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"flink-jobmanager-1|flink-taskmanager-1|flink-app-1|kafka-server|zookeeper|fluentbit|clickhouse|web-server-app|web-server-db|grafana\"} / 1024 / 1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "End-to-End Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(toUnixTimestamp(ingestion_time) - toUnixTimestamp(time)) AS avg_latency_seconds,\n  max(toUnixTimestamp(ingestion_time) - toUnixTimestamp(time)) AS max_latency_seconds,\n  min(toUnixTimestamp(ingestion_time) - toUnixTimestamp(time)) AS min_latency_seconds,\n  quantile(0.5)(toUnixTimestamp(ingestion_time) - toUnixTimestamp(time)) AS p50_latency_seconds,\n  quantile(0.95)(toUnixTimestamp(ingestion_time) - toUnixTimestamp(time)) AS p95_latency_seconds,\n  quantile(0.99)(toUnixTimestamp(ingestion_time) - toUnixTimestamp(time)) AS p99_latency_seconds\nFROM web_server_logs\nWHERE ingestion_time IS NOT NULL AND time IS NOT NULL"
    }
   ]
  },
  {
   "title": "Flink Processing Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(flink_processing_time_ms) AS avg_latency_seconds,\n  max(flink_processing_time_ms) AS max_latency_seconds,\n  min(flink_processing_time_ms) AS min_latency_seconds,\n  quantile(0.5)(flink_processing_time_ms) AS p50_latency_seconds,\n  quantile(0.95)(flink_processing_time_ms) AS p95_latency_seconds,\n  quantile(0.99)(flink_processing_time_ms) AS p99_latency_seconds\nFROM web_server_logs\nWHERE ingestion_time IS NOT NULL AND time IS NOT NULL"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Kafka Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "max by(job_id) (flink_taskmanager_job_task_operator_numRecordsInPerSecond)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clickhouse Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "rawSql": "SELECT \n    toStartOfInterval(event_time, INTERVAL 15 second) AS time_bucket,\n    sum(written_rows) / 60 AS rows_per_second_avg\nFROM system.query_log\nWHERE event_time >= now() - INTERVAL 1 hour\n    AND type = 'QueryFinish' \n    AND written_rows > 0\nGROUP BY time_bucket\nORDER BY time_bucket;"
    }
   ]
  }
 ]
}