{
 "title": "Final Benchmark",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Resources Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage per Container (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\"flink-jobmanager-1|flink-taskmanager-1|flink-app-1|kafka-server|zookeeper|fluentbit|clickhouse|web-server-app|web-server-db|grafana\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{name=~\"flink-jobmanager-1|flink-taskmanager-1|flink-app-1|kafka-server|zookeeper|fluentbit|clickhouse|web-server-app|web-server-db|grafana\"}[5m]) / 1024 / 1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "End-to-End Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(ingestion_time, INTERVAL 1 minute) AS time_bucket,\n  avg(toUnixTimestamp(ingestion_time) - toUnixTimestamp(time)) AS avg_latency_seconds,\n  max(toUnixTimestamp(ingestion_time) - toUnixTimestamp(time)) AS max_latency_seconds,\n  min(toUnixTimestamp(ingestion_time) - toUnixTimestamp(time)) as min_latency_seconds,\n  quantile(0.5)(toUnixTimestamp(ingestion_time) - toUnixTimestamp(time)) as p50_latency_seconds,\n  quantile(0.95)(toUnixTimestamp(ingestion_time) - toUnixTimestamp(time)) as p95_latency_seconds,\n  quantile(0.99)(toUnixTimestamp(ingestion_time) - toUnixTimestamp(time)) as p99_latency_seconds\n  -- count() AS events\nFROM web_server_logs\nWHERE ingestion_time >= now() - INTERVAL 1 hour\nGROUP BY time_bucket\nORDER BY time_bucket"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Kafka Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_numRecordsIn[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clickhouse Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(ingestion_time, INTERVAL 1 minute) AS time_bucket,\n  count() AS logs_ingested\nFROM web_server_logs\nWHERE ingestion_time >= now() - INTERVAL 1 hour\nGROUP BY time_bucket\nORDER BY time_bucket"
    }
   ]
  }
 ]
}