version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - log-monitor-network
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
  
networks:
  log-monitor-network:
    external: true