version: '3'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - log-monitor-network

volumes:
  redis_data:


networks:
  log-monitor-network:
    external: true
